### ISSUE TITLE
i have problem whit downloading umf 

### ISSUE THREAD

**Issue by foxypayz** [Thomasims/TeardownUMF-Examples#1]
basically, i downloaded how it said in the guide but it doesn't work I add mod and it only shows this 
![Screenshot_160](https://user-images.githubusercontent.com/76434828/102776971-58de8480-4398-11eb-9b85-b45d8b38b579.png)

**Comment by Thomasims** [comment]
The missing gChallengesScale tells me you're running the latest version on UMF on a game version < 0.5.1.
Make sure you're running the latest experimental version of the game and reinstall UMF.

**Comment by foxypayz** [comment]
The thing is when i download it says nevest version is 0.5.0 so perhaps can
you give link to newest?

**Comment by Thomasims** [comment]
The game has been updated to 0.5.2 and so has UMF. You can now use the latest version available [here](https://github.com/Thomasims/TeardownUMF).
